
// WEB3 REDUCER
export const SET_WEB3_INSTANCE = 'SET_WEB3_INSTANCE';
export const ADD_CONTRACT = 'ADD_CONTRACT';
export const SET_INITIALIZED = 'SET_INITIALIZED';

// TX HANDLER
export const SET_TX_LOADING = 'SET_TX_LOADING';
export const SET_TX_SUCCESS = 'SET_TX_SUCCESS';
export const SET_TX_ERROR = 'SET_TX_ERROR';

//WALLET REDUCER
export const SET_WALLET = 'SET_WALLET';
export const SET_NETWORK_ID = 'SET_NETWORK_ID';
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
